apps/adopcion/urls.py
from django.conf.urls import url
from apps.adopcion.views import SolicitudCreate, SolicitudList, SolicitudUpdate, SolicitudDelete

urlpatterns = [

    url(r'^solicitud/listar', SolicitudList.as_view(), name='solicitud_listar'),
    url(r'^solicitud/crear', SolicitudCreate.as_view(), name='solicitud_crear'),
    url(r'^solicitud/editar/(?P<pk>\d+)/$', SolicitudUpdate.as_view(), name='solicitud_editar'),
    url(r'^solicitud/eliminar/(?P<pk>\d+)/$', SolicitudDelete.as_view(), name='solicitud_eliminar'),
]

apps/mascota/urls.py
from django.conf.urls import url, include

from apps.mascota.views import index, mascotaView, mascotaList, mascotaEdit, mascotaDelete, Mascota_List, Mascota_Create\
    , Mascota_Update, Mascota_Delete

from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', login_required(Mascota_Create.as_view()), name='mascota_crear'),
    url(r'^lista$', login_required(Mascota_List.as_view()), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(Mascota_Update.as_view()), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)$',login_required(Mascota_Delete.as_view()), name='mascota_eliminar')
]

refugio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login, password_reset,password_reset_done, password_reset_confirm,\
    password_reset_complete, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls',namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls',namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls',namespace="usuario")),
    url(r'^accounts/login/$',login,{'template_name':'login.html'},name='login'),
    url(r'^logout$', logout_then_login, name='logout'),
    url(r'^reset/password_reset/$',password_reset,{'template_name':'registration/password_reset_form.html',
                                                 'email_template_name': 'registration/password_reset_email.html'}
        ,name='password_reset'),
    url(r'^reset/password_reset_done/$',password_reset_done,{'template_name':'registration/password_reset_done.html'}
        ,name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',password_reset_confirm
        ,{'template_name':'registration/password_reset_confirm.html'}
        ,name='password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete,{'template_name':'registration/password_reset_complete.html'}
        ,name='password_reset_complete'),

]

apps/adopcion/models.py
from django.db import models

# Create your models here.


class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=12)
    email= models.EmailField()
    domicilio = models.TextField()
    def __str__(self):
        return '{} {}'.format(self.nombre, self.apellidos)


class Solicitud(models.Model):
    persona = models.ForeignKey(Persona, null=True, blank=True)
    numero_de_mascotas = models.IntegerField()
    razones = models.TextField()

apps/adopcion/forms.py
from django import forms
from apps.adopcion.models import Persona, Solicitud

class PersonaForm(forms.ModelForm):

    class Meta:
        model = Persona

        fields = [
            'nombre',
            'apellidos',
            'edad',
            'telefono',
            'email',
            'domicilio',
        ]
        labels = {
            'nombre' : 'Nombre',
            'apellidos' : 'Apellidos',
            'edad' : 'Edad',
            'telefono' : 'Telefono',
            'email' : 'Email',
            'domicilio' : 'Direccion de vivienda',
        }
        widgets = {
            'nombre' : forms.TextInput(attrs={'class': 'form-control'}),
            'apellidos' : forms.TextInput(attrs={'class': 'form-control'}),
            'edad' : forms.TextInput(attrs={'class': 'form-control'}),
            'telefono' : forms.TextInput(attrs={'class': 'form-control'}),
            'email' : forms.EmailInput(attrs={'class': 'form-control'}),
            'domicilio' : forms.TextInput(attrs={'class': 'form-control'}),
        }

class SolicitudForm(forms.ModelForm):
    class Meta:
        model = Solicitud

        fields = [
            'numero_de_mascotas',
            'razones',
        ]
        labels = {
            'numero_de_mascotas' : 'Numero de mascotas',
            'razones' : 'Razones',
        }
        widgets = {
            'numero_de_mascotas' : forms.TextInput(attrs={'class':'form-control'}),
            'razones': forms.TextInput(attrs={'class':'form-control'}),
        }

apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DeleteView, UpdateView, CreateView
from apps.adopcion.models import Persona, Solicitud
from apps.adopcion.forms import SolicitudForm, PersonaForm
from django.core.urlresolvers import reverse_lazy
# Create your views here.


class SolicitudList(ListView):
    model = Solicitud
    template_name = 'adopcion/solicitud_list.html'

class SolicitudCreate(CreateView):
    model = Solicitud
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')

    def get_context_data(self, **kwargs):
        context = super(SolicitudCreate, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            solicitud = form.save(commit=False)
            solicitud.persona = form2.save()
            solicitud.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form,form2=form2))

class SolicitudUpdate(UpdateView):
    model = Solicitud
    second_model = Persona
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')

    def get_context_data(self, **kwargs):
        context = super(SolicitudUpdate,self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk',0)
        solicitud = self.model.objects.get(id=pk)
        persona = self.second_model.objects.get(id=solicitud.persona_id)
        if 'form' not in context:
            context['form']= self.form_class()
        if 'form2' not in context:
            context['form2']=self.second_form_class(instance=persona)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_solicitud = kwargs['pk']
        solicitud = self.model.objects.get(id=id_solicitud)
        persona = self.second_model.objects.get(id=solicitud.persona_id)
        form = self.form_class(request.POST,instance=solicitud)
        form2 = self.second_form_class(request.POST,instance=persona)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())

class SolicitudDelete(DeleteView):
    model = Solicitud
    template_name = 'adopcion/solicitud_delete.html'
    success_url = reverse_lazy('adopcion:solicitud_listar')

templates/adopcion/solicitud_delete.html
{% extends 'base/base.html'%}

{% block title %}
Eliminar Solicitud
{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    <h3> Desea eliminar la solicitud de esta persona {{ object.persona.nombre }}{{ objet.persona.apellidos }}</h3>

    <button class="btn btn-danger" type="submit">Si, eliminar.</button>
        <a  class="btn btn-light" href="{%   url 'mascota:mascota_listar' %}">Cancelar</a>
    </form>
{% endblock %}

templates/adopcion/solicitud_form.html
{% extends 'base/base.html' %}
{% block title %}
Formulario Solicitud
{% endblock %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        {{ form2.as_p }}
        {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

{% endblock %}

templates/adopcion/solicitud_list.html
{% extends 'base/base.html' %}

{% block title %}
Lista de solicitudes
{% endblock %}

{% block content %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>#</td>
                <td>Adoptante</td>
                <td>No. Mascotas</td>
                <td>Razones</td>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for solicitud in object_list %}
            <tr>
                <td>{{ solicitud.id }}</td>
                <td>{{ solicitud.persona.nombre }} {{ solicitud.persona.apellidos }}</td>
                <td>{{ solicitud.numero_de_mascotas }}</td>
                <td>{{ solicitud.razones }}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'adopcion:solicitud_editar' solicitud.id %}">Editar</a>
                    <a class="btn btn-danger" href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}">Eliminar</a>

                </td>
            </tr>
            {% endfor %}
            {% else %}
            <h1>No hay registros de mascotas</h1>
            {% endif %}
        </tbody>
    </table>
{% endblock %}