apps/adopcion/urls.py
from django.conf.urls import url
from apps.adopcion.views import SolicitudCreate, SolicitudList, SolicitudUpdate, SolicitudDelete

urlpatterns = [

    url(r'^solicitud/listar', SolicitudList.as_view(), name='solicitud_listar'),
    url(r'^solicitud/crear', SolicitudCreate.as_view(), name='solicitud_crear'),
    url(r'^solicitud/editar/(?P<pk>\d+)/$', SolicitudUpdate.as_view(), name='solicitud_editar'),
    url(r'^solicitud/eliminar/(?P<pk>\d+)/$', SolicitudDelete.as_view(), name='solicitud_eliminar'),
]

apps/mascota/urls.py
from django.conf.urls import url, include

from apps.mascota.views import index, mascotaView, mascotaList, mascotaEdit, mascotaDelete, Mascota_List, Mascota_Create\
    , Mascota_Update, Mascota_Delete

from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', login_required(Mascota_Create.as_view()), name='mascota_crear'),
    url(r'^lista$', login_required(Mascota_List.as_view()), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(Mascota_Update.as_view()), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)$',login_required(Mascota_Delete.as_view()), name='mascota_eliminar')
]

apps/usuario/urls.py
from django.conf.urls import url, include

from apps.usuario.views import RegistroUsuarios


urlpatterns = [
    url(r'^registrar/$', RegistroUsuarios.as_view(), name='registrar_usuario'),

]

refugio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login, password_reset,password_reset_done, password_reset_confirm,\
    password_reset_complete, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls',namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls',namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls',namespace="usuario")),
    url(r'^accounts/login/$',login,{'template_name':'login.html'},name='login'),
    url(r'^logout$', logout_then_login, name='logout'),
    url(r'^reset/password_reset/$',password_reset,{'template_name':'registration/password_reset_form.html',
                                                 'email_template_name': 'registration/password_reset_email.html'}
        ,name='password_reset'),
    url(r'^reset/password_reset_done/$',password_reset_done,{'template_name':'registration/password_reset_done.html'}
        ,name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',password_reset_confirm
        ,{'template_name':'registration/password_reset_confirm.html'}
        ,name='password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete,{'template_name':'registration/password_reset_complete.html'}
        ,name='password_reset_complete'),

]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block extrahead %}

    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>{% block title %} Document {% endblock %}</title>
</head>
<body>
<div class="container">
    {%  block navbar %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Refugio</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'login' %}">Login <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuario:registrar_usuario' %}">Registrar</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMascota" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Mascota
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMascota">
                            <a class="dropdown-item" href="{% url 'mascota:mascota_crear' %}">Registrar Mascota</a>
                            <a class="dropdown-item" href="{% url 'mascota:mascota_listar' %}">Listar Mascotas</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAdopcion" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Adopcion
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownAdopcion">
                            <a class="dropdown-item" href="{% url 'adopcion:solicitud_crear' %}">Crear Solicitud</a>
                            <a class="dropdown-item" href="{% url 'adopcion:solicitud_listar' %}">Listar Solicitudes</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="{% url 'logout' %}">Logout</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    {% endblock %}

    {% block content %}
        <h4>Content base</h4>
    {% endblock %}

    {% block footer %}
        <h4>Footer base</h4>
    {% endblock %}
</div>

{% block extrajs %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</body>
</html>