apps/mascota/urls.py
from django.conf.urls import url, include

from apps.mascota.views import index, mascotaView, mascotaList, mascotaEdit, mascotaDelete, Mascota_List, Mascota_Create\
    , Mascota_Update, Mascota_Delete

from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', login_required(Mascota_Create.as_view()), name='mascota_crear'),
    url(r'^lista$', login_required(Mascota_List.as_view()), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(Mascota_Update.as_view()), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)$',login_required(Mascota_Delete.as_view()), name='mascota_eliminar')
]

refugio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login, password_reset,password_reset_done, password_reset_confirm,\
    password_reset_complete, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls',namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls',namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls',namespace="usuario")),
    url(r'^accounts/login/$',login,{'template_name':'login.html'},name='login'),
    url(r'^logout$', logout_then_login, name='logout'),
    url(r'^reset/password_reset/$',password_reset,{'template_name':'registration/password_reset_form.html',
                                                 'email_template_name': 'registration/password_reset_email.html'}
        ,name='password_reset'),
    url(r'^reset/password_reset_done/$',password_reset_done,{'template_name':'registration/password_reset_done.html'}
        ,name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',password_reset_confirm
        ,{'template_name':'registration/password_reset_confirm.html'}
        ,name='password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete,{'template_name':'registration/password_reset_complete.html'}
        ,name='password_reset_complete'),

]

apps/mascota/models.py
from django.db import models

# Create your models here.

from apps.adopcion.models import Persona

class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre)


class Mascota(models.Model):
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona,null=True,blank=True,on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank=True)

    def __str__(self):
        return '{}'.format(self.nombre)

apps/mascota/forms.py
from django import forms
from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):

    class Meta:
        model = Mascota

        fields = [
            'nombre',
            'sexo',
            'edad_aproximada',
            'fecha_rescate',
            'persona',
            'vacuna',
        ]
        labels = {
            'nombre':'Nombre',
            'sexo':'Sexo',
            'edad_aproximada':'Edad aproximada',
            'fecha_rescate':'Fecha de Rescate',
            'persona':'Adoptante',
            'vacuna':'Vacunas',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'sexo': forms.TextInput(attrs={'class':'form-control'}),
            'edad_aproximada': forms.TextInput(attrs={'class':'form-control '}),
            'fecha_rescate': forms.TextInput(attrs={'class':'form-control'}),
            'persona': forms.Select(attrs={'class':'form-control'}),
            'vacuna': forms.CheckboxSelectMultiple(),
        }

apps/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.core.urlresolvers import reverse_lazy

from django.views.generic import ListView, CreateView, DeleteView, UpdateView

from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota

# Create your views here.

def index(request):
    return render(request, 'mascota/index.html')


def mascotaView(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('mascota:index')
    else:
        form = MascotaForm()

    return render(request, 'mascota/mascota_form.html',{'form':form})

def mascotaList(request):
    mascota = Mascota.objects.all()
    contexto = {'mascotas':mascota}
    return render(request,'mascota/mascota_list.html',contexto)

def mascotaEdit(request,id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'GET':
        form = MascotaForm(instance=mascota)
    else:
        form = MascotaForm(request.POST,instance=mascota)
        if (form.is_valid()):
            form.save()
        return redirect('mascota:mascota_listar')
    return render(request,'mascota/mascota_form.html',{'form':form})

def mascotaDelete(request,id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method=='POST':
        mascota.delete()
        return redirect('mascota:mascota_listar')
    return render(request,'mascota/mascota_delete.html',{'mascota':mascota})

class Mascota_List(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'
    ordering = ['id']



class Mascota_Create(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')

class Mascota_Update(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')

class Mascota_Delete(DeleteView):
    model = Mascota
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota:mascota_listar')

templates/mascota/index.html
{% extends 'base/base.html' %}
{% block title %} index mascota {% endblock %}

templates/mascota/mascota_delete.html
{% extends 'base/base.html'%}

{% block title %}
Eliminar Mascota
{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    <h3> Desea eliminar el registro de {{ object.nombre }}</h3>

    <button class="btn btn-danger" type="submit">Si, eliminar.</button>
        <a  class="btn btn-light" href="{%   url 'mascota:mascota_listar' %}">Cancelar</a>
    </form>
{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{  form.as_p }}
    <button class="btn btn-info" type="submit">Guardar</button>
</form>
{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>#</td>
                <td>Nombre</td>
                <td>Sexo</td>
                <td>Edad</td>
                <td>Fecha de Rescate</td>
                <td>Adoptante</td>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for mascota in object_list %}



            <tr>
                <td>{{ mascota.id }}</td>
                <td>{{ mascota.nombre }}</td>
                <td>{{ mascota.sexo }}</td>
                <td>{{ mascota.edad_aproximada }}</td>
                <td>{{ mascota.fecha_rescate }}</td>
                <td>{{ mascota.persona.nombre }} {{ mascota.persona.apellido }}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
                    <a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>

                </td>
            </tr>
            {% endfor %}
            {% else %}
            <h1>No hay registros de mascotas</h1>
            {% endif %}
        </tbody>
    </table>


{% endblock %}